spring:
  application:
    name: bcb-backoffice
  profiles:
    active:
      - production
  jpa:
    hibernate:
        ddl-auto: update
    show-sql: true

server:
  port: 4000
  error:
    include-stacktrace: never

bcb:
  message:
    sms: 
      cost: -0.25
    whatsapp: 
      cost: -0.25

management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: health
  endpoint:
    health:
      enabled: true
